services:
  lab_05_db:
    image: postgres:16
    container_name: lab_05_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5436:5432"
    networks:
      - lab_05_network

  lab_05_pgadmin:
    image: dpage/pgadmin4
    container_name: lab_05_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8086:80"
    depends_on:
      - lab_05_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - lab_05_network

volumes:
  pgadmin_data:

networks:
  lab_05_network:
    external: true
